apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: place-gavinies-wordpress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: place-gavinies
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 22.2.11
    chart: wordpress
    helm:
      valuesObject:
        ingress:
          enabled: true
          hostname: place-gavinies.fr
          ingressClassName: nginx
          tls: true
          tlsWwwPrefix: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
        service:
          type: ClusterIP
