apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resultats
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: resultats
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.2.2
    chart: mariadb
    helm:
      valuesObject:
        primary:
          service:
            type: ClusterIP
