apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.46.3
    chart: argo-cd
    helm:
      valuesObject:
        configs:
          cm:
            timeout.reconciliation: 10s
        server:
          extraArgs:
          - --insecure
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            enabled: true
            hosts:
            - argocd.loicgombeaud.com
            ingressClassName: nginx
            tls:
            - hosts:
              - argocd.loicgombeaud.com
              secretName: argocd-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
